title: Mandiri Agung Yatra
email: info@mandiriagung.co.id
description: Modern digital solutions for your business and management.
baseurl: "" # if in subfolder, fill like "/repo"
url: "https://mandiriagung.co.id"
markdown: kramdown

permalink: /:path/
