title: Mandaguyat
email: info@mandaguyat.com
description: Solusi digital modern untuk bisnis dan pengelolaan Anda.
baseurl: "" # jika di subfolder, isi seperti "/repo"
url: "https://mandaguyat.com"
markdown: kramdown
# theme: mandaguyat
permalink: /:path/
