title: Mandiri Agung Yatra
email: info@mandiriagung.co.id
description: Solusi digital modern untuk bisnis dan pengelolaan Anda.
baseurl: "" # jika di subfolder, isi seperti "/repo"
url: "https://mandiriagung.co.id"
markdown: kramdown
# theme: mandiri-agung-yatra
permalink: /:path/
